# DOCKER PLAYBOOK
---
- name: Install Nginx to web hosts
  hosts: "web"
  become: true
  roles:
    - nginx

- name: Install Docker to app hosts
  hosts: "app"
  become: true
  roles:
    - docker

  tasks:
    - name: Run Docker container
      docker_container:
        name: django-app
        image: timurbabs/django:latest
        state: started
        ports:
          - "8000:8000"

    - name: timeout for check
      pause:
        seconds: 10

    - name: Check app running
      uri:
        url: "http://158.160.138.244:8000"
        return_content: yes
      register: app_response

    - name: Output main page content
      debug:
        var: app_response.content

    - name: Check app running
      uri:
        url: "http://158.160.148.96/"
        status_code: 200
        return_content: yes
      register: response

    - debug:
        var: response.content


