---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Git
  apt:
    name: git
    state: present

- name: Verify Git installation
  command: git --version
  register: git_version

- name: Display Git version
  debug:
    msg: "Git version: {{ git_version.stdout }}"
